name: CI & Deploy → Cloud Run

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # Java 21
      - name: Set up GraalVM 21
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'
          cache: 'maven'

      # build & enforce coverage
      - name: Cache Maven dependencies
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-m2-
      - name: Build native + enforce coverage
        run: mvn clean package -Pnative test

      - name: Upload coverage report
        uses: actions/upload-artifact@v4
        with:
          name: jacoco-report
          path: target/site/jacoco/jacoco.xml

  deploy:
    needs: build
    if: ${{ needs.build.result == 'success' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Authenticate to GCP
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Set Project
        run: gcloud config set project ${{ secrets.GCP_PROJECT_ID }}

      - name: Configure Docker for Artifact Registry
        run: |
          gcloud auth configure-docker asia-southeast2-docker.pkg.dev --quiet

      - name: Build & push native image
        run: |
          IMAGE_URI=asia-southeast2-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/my-docker-repo/bolt-track:$GITHUB_SHA
          docker build -t $IMAGE_URI .
          docker push $IMAGE_URI

      - name: Deploy to Cloud Run
        uses: google-github-actions/deploy-cloudrun@v0
        with:
          service: bolt-track
          image: asia-southeast2-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/my-docker-repo/bolt-track:$GITHUB_SHA
          region: asia-southeast2
          allow_unauthenticated: true
          secret_env_vars: |
            REDIS_PASS=projects/${{ secrets.GCP_PROJECT_ID }}/secrets/mongodb_atlas_porto/versions/latest
            MONGODB_PASS_ADM=projects/${{ secrets.GCP_PROJECT_ID }}/secrets/upstash_pass/versions/latest
