name: CI & Deploy → Cloud Run

on:
  push:
    branches:
      - main

env:
  GCP_PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
  IMAGE_NAME: gcr.io/${{ secrets.GCP_PROJECT_ID }}/bolt-track

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: '21'
          cache: maven

      - name: Build & publish image with Spring Boot Buildpacks
        run: |
          mvn -B -Pnative spring-boot:build-image \
            -Dspring-boot.build-image.builder=paketobuildpacks/builder:tiny \
            -Dspring-boot.build-image.imageName=${{ env.IMAGE_NAME }}:${{ github.sha }} \
            -Dspring-boot.build-image.publish=true

      - name: Upload JaCoCo report
        uses: actions/upload-artifact@v4
        with:
          name: jacoco-report
          path: target/site/jacoco/jacoco.xml

  deploy:
    needs: build
    if: ${{ needs.build.result == 'success' }}
    runs-on: ubuntu-latest
    steps:
      - name: Authenticate to GCP
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Configure gcloud
        run: |
          gcloud config set project ${{ env.GCP_PROJECT_ID }}

      - name: Build & push native image
        run: |
          docker build -t gcr.io/${{ secrets.GCP_PROJECT_ID }}/bolt-track:$GITHUB_SHA .
          docker push gcr.io/${{ secrets.GCP_PROJECT_ID }}/bolt-track:$GITHUB_SHA

      - name: Deploy to Cloud Run using Buildpack image
        uses: google-github-actions/deploy-cloudrun@v0
        with:
          service: bolt-track
          image: ${{ env.IMAGE_NAME }}:${{ github.sha }}
          region: asia-southeast2
          allow_unauthenticated: true
          secret_env_vars: |
            REDIS_PASS=projects/${{ env.GCP_PROJECT_ID }}/secrets/redis-pass/versions/latest
            MONGODB_PASS_ADM=projects/${{ env.GCP_PROJECT_ID }}/secrets/upstash_pass/versions/latest
          env_vars: |
            SPRING_PROFILES_ACTIVE=prod
