name: CI & Deploy → Cloud Run

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # 1) Java 21
      - name: Set up GraalVM 21
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'
          cache: 'maven'

      # 2) install native-image
      - name: Install GraalVM native-image
        run: gu install native-image

      # 3) build & enforce coverage
      - name: Build native + enforce coverage
        run: mvn clean package -Pnative test

      - name: Upload coverage report
        uses: actions/upload-artifact@v4
        with:
          name: jacoco-report
          path: target/site/jacoco/jacoco.xml

  deploy:
    needs: build
    if: ${{ needs.build.result == 'success' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Authenticate to GCP
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Set Project
        run: gcloud config set project ${{ secrets.GCP_PROJECT_ID }}

      - name: Build & push native image
        run: |
          docker build -t gcr.io/${{ secrets.GCP_PROJECT_ID }}/bolt-track:$GITHUB_SHA .
          docker push gcr.io/${{ secrets.GCP_PROJECT_ID }}/bolt-track:$GITHUB_SHA

      - name: Deploy to Cloud Run
        uses: google-github-actions/deploy-cloudrun@v0
        with:
          service: bolt-track
          image: gcr.io/${{ secrets.GCP_PROJECT_ID }}/bolt-track:$GITHUB_SHA
          region: asia-southeast2
          allow_unauthenticated: true
          secret_env_vars: |
            REDIS_PASS=projects/${{ secrets.GCP_PROJECT_ID }}/secrets/mongodb_atlas_porto/versions/latest
            MONGODB_PASS_ADM=projects/${{ secrets.GCP_PROJECT_ID }}/secrets/upstash_pass/versions/latest
